### ISSUE TITLE
Fatal Error after removing outfit_restrictions from outfit

### ISSUE THREAD

**Issue by lucius-martius** [ahuyn/anomaly-opo#3]
After recently coming back to Anomaly I found that the [Seperate Helmets Outfitsd and Backpack](https://www.moddb.com/mods/stalker-anomaly/addons/separated-helmets-outfits-backpacks) mod did not work with this mod anymore. As soon as the actor gets hit by an NPC it results in the following error:

![Screenshot_20220226_163917](https://user-images.githubusercontent.com/10165955/155849205-eb295165-6cb3-4ec3-bed5-149102e42607.jpg)

I tried to bisect the issue and found that removing outfit restrictions in `config/items/outfits/base/base.ltx` is what is causing the error. This can be in the form of switching the outfit_restritions bases around (like on one of the exos from `outfit_restrictions_3` to `outfit_restrictions_1` to enable the backpack slot. Also directly removing one of the restrictions (like `backpack_avaliable = false`) from the bases themselves causes the same result.

I have not been able to track it any further and since I am unfamiliar with LUA and your code, so I kindly ask you to take a look into what causes the crash.

**Steps to reproduce**:

- Start with a clean Anomaly install
- unpack config files from `db/configs/configs.db0`
- Install anomaly-opo
- Edit `configs/items/outfits/o_exoskeleton.ltx` and set `bandit_exo_outfit` from `outfit_restrictions_3` to `outfit_restrictions_1`
- Start new game and spawn in and wear bandit exo using debug mode
- Shoot NPC and get shot at
- Witness the above crash

Please feel free to tell me if I can do anything to help debug this further.

**Comment by ahuyn** [comment]
Thanks for bringing this up to me. This is actually not related to the outfit base, but it is a bug with exoskeletons.

To explain:

When the player takes damage, damage is applied to each outfit component with a multiplier - the base value being the condition damage the suit would normally take. Each type of component is associated with a 'rank' from 1-5, and that rank is used to determine the multiplier.

The rank of the exo frames (prt_o_support_1) is supposed to be 5, but was accidentally overriden into something else. I will fix this.

**Comment by lucius-martius** [comment]
Just tested the new version and it works fine now. Thanks for fixing it so quickly.
